### ISSUE TITLE
Hydration error when using Keeper password manager chrome extension

### ISSUE THREAD

**Issue by Nicolascanala** [vercel/nextjs-postgres-auth-starter#14]
Hi,

I'm having some issues with a fresh install when using the Keeper password manager chrome extension.

**Error**: Unhandled Runtime Error
Error: Hydration failed because the initial UI does not match what was rendered on the server.

This extension adds some attributes to the markup, in particular to the login/register forms. After some debugging, I noticed that when disabling the extension, the error no longer shows up. The attribute added to the inputs is: data-keeper-lock-id="...".

The error makes sense somewhat, but still feels like a bug.

Please let me know if there is something that can be done about this. For now, I will just develop with the extension turned off, but I wonder if this would happen when deploying the app as well.

All the best.

**Comment by salacoste** [comment]
confirm 
That was actually so hardly debugged, I went through all code and dependencies.. 
<img width="676" alt="image" src="https://user-images.githubusercontent.com/12632895/222858481-0024e5a4-04f5-43af-ac85-365e31ca6234.png">

**Comment by aed0nis** [comment]
Can confirm this as well. I get this error when using dashlane, but don't get this error when I use browser with it disabled.

**Comment by Yukinosuke-Takada** [comment]
I also used way too much time debugging this. I believe any extension that injects elements into the DOM can cause this issue notably: password managers, and typing assistant tools. To avoid getting this error I'm using Chrome's Incognito window for development.

**Comment by leerob** [comment]
Yeah, unfortunately this is just due to the browser extensions 😢
