### ISSUE TITLE
Just a Question (No Issue)

### ISSUE THREAD

**Issue by TilP** [vercel/nextjs-postgres-auth-starter#17]
Hi Guys,

Pardon my incompetence here, I am relearning Next (used it once three years ago)...   Just wondering how the redirect happens (and where the code is) for /protected when not logged in.

I saw the getServerSession, will try tracing from there...  Thanks

**Comment by abtonc** [comment]
Hi! Redirect happens here: https://github.com/vercel/nextjs-mysql-auth-starter/blob/708d6d5880a9a314b9e29514195a463fb99a7471/middleware.ts

**Comment by donfour** [comment]
Also a noob question, why doesn't something like this work?
```
export { default } from "next-auth/middleware";
export const config = { matcher: ["/protected"] };
```

I tried and the redirect after sign in doesn't work.
