### ISSUE TITLE
Can i contribute to this repo?

### ISSUE THREAD

**Issue by vguleaev** [vercel/nextjs-postgres-auth-starter#18]
I want to make PR with a change about removing ts-ignore comment but I get access denied when i try to push a branch. 😃

**Comment by abtonc** [comment]
You can fork the repo > make your changes and then create a new pull request, that's the healthiest way.

**Comment by leerob** [comment]
Just pushed some new updates, feel free to fork and PR back if you see anything! 

https://github.com/vercel/nextjs-postgres-auth-starter/pull/48
