### ISSUE TITLE
Session data not being displayed on initial login?

### ISSUE THREAD

**Issue by JustinRR** [vercel/nextjs-postgres-auth-starter#20]
Hello! Just a quick question. I have the same "issue" as the example at: https://nextjs-mysql-auth.vercel.app/

Is there a reason why, when after successful login, that the session data doesn't show at the top of the page?

For me, it does not display once logged in, initially. But if I refresh the page after I am logged in, it shows up.

Is this by design or am I missing something?

Thanks!

**Comment by leerob** [comment]
https://github.com/vercel/nextjs-postgres-auth-starter/pull/48
