### ISSUE TITLE
Why login pages request '/registe'

### ISSUE THREAD

**Issue by AnsonZnl** [vercel/nextjs-postgres-auth-starter#32]
see image
![image](https://github.com/vercel/nextjs-postgres-auth-starter/assets/29278068/3dcac07d-e350-4b8d-90d3-f2e78e7f8ae3)

**Comment by AnsonZnl** [comment]
I dot't know where it sent the request

**Comment by AnsonZnl** [comment]
I seem to know. this is the Link for Next.js feature?

**Comment by leerob** [comment]
Changed in https://github.com/vercel/nextjs-postgres-auth-starter/pull/48.
