### ISSUE TITLE
Next.js Prisma Postgres Auth Starter

### ISSUE THREAD

**Issue by matzeso** [vercel/nextjs-postgres-auth-starter#47]
Hey there,
when deploying this starter: https://vercel.com/templates/next.js/prisma-postgres-auth-starter
and changing the postgres env prefix from `POSTGRES` to e.g. `PG` then the starter fails to deploy because the code still expects the `POSTGRES` prefix for prisma env vars.

**Comment by leerob** [comment]
Correct, you would need to make code modifications here as well if you change the environment variable names 👍
