### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by dikaio** [vercel/nextjs-postgres-auth-starter#52]
I received this error while registering and signing into the demo application.

`Failed to load resource: the server responded with a status of 500 ()`

`Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.`

**Comment by leerob** [comment]
![CleanShot 2024-01-30 at 19 46 02@2x](https://github.com/vercel/nextjs-postgres-auth-starter/assets/9113740/6592961f-033f-4796-b6bd-6f2a21046efa)

Hmm, seems to be working okay for me. Could you explain more?

**Comment by dikaio** [comment]
Hi @leerob. I've tried to locate find anything else that could help but this is all that I could come up, here's the step I'm taking.

1. <https://nextjs-postgres-auth.vercel.app/register> and register, but I'm never redirected or confirmed to be registered. The button does show the spinner and when it stops nothing happens. It's almost as if my Post is being blocked.
2. <https://nextjs-postgres-auth.vercel.app/login> I check to see if I was registered and log in but this is where I get the error message `Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 2130482681` and references I've added the [output to a gist](https://gist.githubusercontent.com/dikaio/4249e85ef38803e743526f23d66bd7d3/raw/e3f05c26b8ece8d971213070e4df4ee255121b8e/815-a8aaaeea819b17ce.js) but I believe this is just the normal output.

At first, I thought it might be a VPN that I was using, but I did disable the VPN and also tried Safari and Chrome browsers but no luck. Is there anything else I can do on this end that might help?

**Comment by dikaio** [comment]
I did just try logging out and clearing my cache, but I am still having issues. There are no warnings or messages in the console while trying to sign up. Not sure where else to go from here but would be more than happy to try and help troubleshoot it, is there anything else I can do from here?
